"""Static reference data for the editor: regions, species names, gender buckets.

Generated by ``scripts/fetch_pokeapi_data.py`` from PokeAPI
(https://pokeapi.co). To regenerate, run that script and commit this file.

The bucket data drives :meth:`pcedit_gui.PokedexTab._bump_stats`: when a user
opts into stat back-fill while marking pokémon caught, the right
``save.statistics.total<…>PokemonCaptured`` counter is incremented per species.
"""
from __future__ import annotations

# Region IDs match PokeClicker's national-dex grouping. Hisui shares numbers
# with prior generations and is not exposed as its own range here.


REGION_RANGES: list[tuple[str, int, int]] = [
    ("Kanto",   1,    151),
    ("Johto",   152,  251),
    ("Hoenn",   252,  386),
    ("Sinnoh",  387,  493),
    ("Unova",   494,  649),
    ("Kalos",   650,  721),
    ("Alola",   722,  809),
    ("Galar",   810,  905),
    ("Paldea",  906,  1025),
]


# National-dex display names, indexed by pid - 1.
# Generated from PokeAPI; see scripts/fetch_pokeapi_data.py.
NATIONAL_NAMES: list[str] = [
    # --- Kanto (#1+)
    'Bulbasaur', 'Ivysaur', 'Venusaur', 'Charmander', 'Charmeleon', 'Charizard',
    'Squirtle', 'Wartortle', 'Blastoise', 'Caterpie', 'Metapod', 'Butterfree',
    'Weedle', 'Kakuna', 'Beedrill', 'Pidgey', 'Pidgeotto', 'Pidgeot',
    'Rattata', 'Raticate', 'Spearow', 'Fearow', 'Ekans', 'Arbok',
    'Pikachu', 'Raichu', 'Sandshrew', 'Sandslash', 'Nidoran♀', 'Nidorina',
    'Nidoqueen', 'Nidoran♂', 'Nidorino', 'Nidoking', 'Clefairy', 'Clefable',
    'Vulpix', 'Ninetales', 'Jigglypuff', 'Wigglytuff', 'Zubat', 'Golbat',
    'Oddish', 'Gloom', 'Vileplume', 'Paras', 'Parasect', 'Venonat',
    'Venomoth', 'Diglett', 'Dugtrio', 'Meowth', 'Persian', 'Psyduck',
    'Golduck', 'Mankey', 'Primeape', 'Growlithe', 'Arcanine', 'Poliwag',
    'Poliwhirl', 'Poliwrath', 'Abra', 'Kadabra', 'Alakazam', 'Machop',
    'Machoke', 'Machamp', 'Bellsprout', 'Weepinbell', 'Victreebel', 'Tentacool',
    'Tentacruel', 'Geodude', 'Graveler', 'Golem', 'Ponyta', 'Rapidash',
    'Slowpoke', 'Slowbro', 'Magnemite', 'Magneton', "Farfetch'd", 'Doduo',
    'Dodrio', 'Seel', 'Dewgong', 'Grimer', 'Muk', 'Shellder',
    'Cloyster', 'Gastly', 'Haunter', 'Gengar', 'Onix', 'Drowzee',
    'Hypno', 'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Exeggcute',
    'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan', 'Lickitung',
    'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon', 'Chansey', 'Tangela',
    'Kangaskhan', 'Horsea', 'Seadra', 'Goldeen', 'Seaking', 'Staryu',
    'Starmie', 'Mr. Mime', 'Scyther', 'Jynx', 'Electabuzz', 'Magmar',
    'Pinsir', 'Tauros', 'Magikarp', 'Gyarados', 'Lapras', 'Ditto',
    'Eevee', 'Vaporeon', 'Jolteon', 'Flareon', 'Porygon', 'Omanyte',
    'Omastar', 'Kabuto', 'Kabutops', 'Aerodactyl', 'Snorlax', 'Articuno',
    'Zapdos', 'Moltres', 'Dratini', 'Dragonair', 'Dragonite', 'Mewtwo',
    'Mew', 'Chikorita', 'Bayleef', 'Meganium', 'Cyndaquil', 'Quilava',
    'Typhlosion', 'Totodile', 'Croconaw', 'Feraligatr', 'Sentret', 'Furret',
    'Hoothoot', 'Noctowl', 'Ledyba', 'Ledian', 'Spinarak', 'Ariados',
    'Crobat', 'Chinchou', 'Lanturn', 'Pichu', 'Cleffa', 'Igglybuff',
    'Togepi', 'Togetic', 'Natu', 'Xatu', 'Mareep', 'Flaaffy',
    'Ampharos', 'Bellossom', 'Marill', 'Azumarill', 'Sudowoodo', 'Politoed',
    'Hoppip', 'Skiploom', 'Jumpluff', 'Aipom', 'Sunkern', 'Sunflora',
    'Yanma', 'Wooper', 'Quagsire', 'Espeon', 'Umbreon', 'Murkrow',
    'Slowking', 'Misdreavus', 'Unown', 'Wobbuffet', 'Girafarig', 'Pineco',
    'Forretress', 'Dunsparce', 'Gligar', 'Steelix', 'Snubbull', 'Granbull',
    'Qwilfish', 'Scizor', 'Shuckle', 'Heracross', 'Sneasel', 'Teddiursa',
    'Ursaring', 'Slugma', 'Magcargo', 'Swinub', 'Piloswine', 'Corsola',
    'Remoraid', 'Octillery', 'Delibird', 'Mantine', 'Skarmory', 'Houndour',
    'Houndoom', 'Kingdra', 'Phanpy', 'Donphan', 'Porygon2', 'Stantler',
    'Smeargle', 'Tyrogue', 'Hitmontop', 'Smoochum', 'Elekid', 'Magby',
    'Miltank', 'Blissey', 'Raikou', 'Entei', 'Suicune', 'Larvitar',
    'Pupitar', 'Tyranitar', 'Lugia', 'Ho-Oh', 'Celebi', 'Treecko',
    'Grovyle', 'Sceptile', 'Torchic', 'Combusken', 'Blaziken', 'Mudkip',
    'Marshtomp', 'Swampert', 'Poochyena', 'Mightyena', 'Zigzagoon', 'Linoone',
    'Wurmple', 'Silcoon', 'Beautifly', 'Cascoon', 'Dustox', 'Lotad',
    'Lombre', 'Ludicolo', 'Seedot', 'Nuzleaf', 'Shiftry', 'Taillow',
    'Swellow', 'Wingull', 'Pelipper', 'Ralts', 'Kirlia', 'Gardevoir',
    'Surskit', 'Masquerain', 'Shroomish', 'Breloom', 'Slakoth', 'Vigoroth',
    'Slaking', 'Nincada', 'Ninjask', 'Shedinja', 'Whismur', 'Loudred',
    'Exploud', 'Makuhita', 'Hariyama', 'Azurill', 'Nosepass', 'Skitty',
    'Delcatty', 'Sableye', 'Mawile', 'Aron', 'Lairon', 'Aggron',
    'Meditite', 'Medicham', 'Electrike', 'Manectric', 'Plusle', 'Minun',
    'Volbeat', 'Illumise', 'Roselia', 'Gulpin', 'Swalot', 'Carvanha',
    'Sharpedo', 'Wailmer', 'Wailord', 'Numel', 'Camerupt', 'Torkoal',
    'Spoink', 'Grumpig', 'Spinda', 'Trapinch', 'Vibrava', 'Flygon',
    'Cacnea', 'Cacturne', 'Swablu', 'Altaria', 'Zangoose', 'Seviper',
    'Lunatone', 'Solrock', 'Barboach', 'Whiscash', 'Corphish', 'Crawdaunt',
    'Baltoy', 'Claydol', 'Lileep', 'Cradily', 'Anorith', 'Armaldo',
    'Feebas', 'Milotic', 'Castform', 'Kecleon', 'Shuppet', 'Banette',
    'Duskull', 'Dusclops', 'Tropius', 'Chimecho', 'Absol', 'Wynaut',
    'Snorunt', 'Glalie', 'Spheal', 'Sealeo', 'Walrein', 'Clamperl',
    'Huntail', 'Gorebyss', 'Relicanth', 'Luvdisc', 'Bagon', 'Shelgon',
    'Salamence', 'Beldum', 'Metang', 'Metagross', 'Regirock', 'Regice',
    'Registeel', 'Latias', 'Latios', 'Kyogre', 'Groudon', 'Rayquaza',
    'Jirachi', 'Deoxys', 'Turtwig', 'Grotle', 'Torterra', 'Chimchar',
    'Monferno', 'Infernape', 'Piplup', 'Prinplup', 'Empoleon', 'Starly',
    'Staravia', 'Staraptor', 'Bidoof', 'Bibarel', 'Kricketot', 'Kricketune',
    'Shinx', 'Luxio', 'Luxray', 'Budew', 'Roserade', 'Cranidos',
    'Rampardos', 'Shieldon', 'Bastiodon', 'Burmy', 'Wormadam', 'Mothim',
    'Combee', 'Vespiquen', 'Pachirisu', 'Buizel', 'Floatzel', 'Cherubi',
    'Cherrim', 'Shellos', 'Gastrodon', 'Ambipom', 'Drifloon', 'Drifblim',
    'Buneary', 'Lopunny', 'Mismagius', 'Honchkrow', 'Glameow', 'Purugly',
    'Chingling', 'Stunky', 'Skuntank', 'Bronzor', 'Bronzong', 'Bonsly',
    'Mime Jr.', 'Happiny', 'Chatot', 'Spiritomb', 'Gible', 'Gabite',
    'Garchomp', 'Munchlax', 'Riolu', 'Lucario', 'Hippopotas', 'Hippowdon',
    'Skorupi', 'Drapion', 'Croagunk', 'Toxicroak', 'Carnivine', 'Finneon',
    'Lumineon', 'Mantyke', 'Snover', 'Abomasnow', 'Weavile', 'Magnezone',
    'Lickilicky', 'Rhyperior', 'Tangrowth', 'Electivire', 'Magmortar', 'Togekiss',
    'Yanmega', 'Leafeon', 'Glaceon', 'Gliscor', 'Mamoswine', 'Porygon-Z',
    'Gallade', 'Probopass', 'Dusknoir', 'Froslass', 'Rotom', 'Uxie',
    'Mesprit', 'Azelf', 'Dialga', 'Palkia', 'Heatran', 'Regigigas',
    'Giratina', 'Cresselia', 'Phione', 'Manaphy', 'Darkrai', 'Shaymin',
    'Arceus', 'Victini', 'Snivy', 'Servine', 'Serperior', 'Tepig',
    'Pignite', 'Emboar', 'Oshawott', 'Dewott', 'Samurott', 'Patrat',
    'Watchog', 'Lillipup', 'Herdier', 'Stoutland', 'Purrloin', 'Liepard',
    'Pansage', 'Simisage', 'Pansear', 'Simisear', 'Panpour', 'Simipour',
    'Munna', 'Musharna', 'Pidove', 'Tranquill', 'Unfezant', 'Blitzle',
    'Zebstrika', 'Roggenrola', 'Boldore', 'Gigalith', 'Woobat', 'Swoobat',
    'Drilbur', 'Excadrill', 'Audino', 'Timburr', 'Gurdurr', 'Conkeldurr',
    'Tympole', 'Palpitoad', 'Seismitoad', 'Throh', 'Sawk', 'Sewaddle',
    'Swadloon', 'Leavanny', 'Venipede', 'Whirlipede', 'Scolipede', 'Cottonee',
    'Whimsicott', 'Petilil', 'Lilligant', 'Basculin', 'Sandile', 'Krokorok',
    'Krookodile', 'Darumaka', 'Darmanitan', 'Maractus', 'Dwebble', 'Crustle',
    'Scraggy', 'Scrafty', 'Sigilyph', 'Yamask', 'Cofagrigus', 'Tirtouga',
    'Carracosta', 'Archen', 'Archeops', 'Trubbish', 'Garbodor', 'Zorua',
    'Zoroark', 'Minccino', 'Cinccino', 'Gothita', 'Gothorita', 'Gothitelle',
    'Solosis', 'Duosion', 'Reuniclus', 'Ducklett', 'Swanna', 'Vanillite',
    'Vanillish', 'Vanilluxe', 'Deerling', 'Sawsbuck', 'Emolga', 'Karrablast',
    'Escavalier', 'Foongus', 'Amoonguss', 'Frillish', 'Jellicent', 'Alomomola',
    'Joltik', 'Galvantula', 'Ferroseed', 'Ferrothorn', 'Klink', 'Klang',
    'Klinklang', 'Tynamo', 'Eelektrik', 'Eelektross', 'Elgyem', 'Beheeyem',
    'Litwick', 'Lampent', 'Chandelure', 'Axew', 'Fraxure', 'Haxorus',
    'Cubchoo', 'Beartic', 'Cryogonal', 'Shelmet', 'Accelgor', 'Stunfisk',
    'Mienfoo', 'Mienshao', 'Druddigon', 'Golett', 'Golurk', 'Pawniard',
    'Bisharp', 'Bouffalant', 'Rufflet', 'Braviary', 'Vullaby', 'Mandibuzz',
    'Heatmor', 'Durant', 'Deino', 'Zweilous', 'Hydreigon', 'Larvesta',
    'Volcarona', 'Cobalion', 'Terrakion', 'Virizion', 'Tornadus', 'Thundurus',
    'Reshiram', 'Zekrom', 'Landorus', 'Kyurem', 'Keldeo', 'Meloetta',
    'Genesect', 'Chespin', 'Quilladin', 'Chesnaught', 'Fennekin', 'Braixen',
    'Delphox', 'Froakie', 'Frogadier', 'Greninja', 'Bunnelby', 'Diggersby',
    'Fletchling', 'Fletchinder', 'Talonflame', 'Scatterbug', 'Spewpa', 'Vivillon',
    'Litleo', 'Pyroar', 'Flabébé', 'Floette', 'Florges', 'Skiddo',
    'Gogoat', 'Pancham', 'Pangoro', 'Furfrou', 'Espurr', 'Meowstic',
    'Honedge', 'Doublade', 'Aegislash', 'Spritzee', 'Aromatisse', 'Swirlix',
    'Slurpuff', 'Inkay', 'Malamar', 'Binacle', 'Barbaracle', 'Skrelp',
    'Dragalge', 'Clauncher', 'Clawitzer', 'Helioptile', 'Heliolisk', 'Tyrunt',
    'Tyrantrum', 'Amaura', 'Aurorus', 'Sylveon', 'Hawlucha', 'Dedenne',
    'Carbink', 'Goomy', 'Sliggoo', 'Goodra', 'Klefki', 'Phantump',
    'Trevenant', 'Pumpkaboo', 'Gourgeist', 'Bergmite', 'Avalugg', 'Noibat',
    'Noivern', 'Xerneas', 'Yveltal', 'Zygarde', 'Diancie', 'Hoopa',
    'Volcanion', 'Rowlet', 'Dartrix', 'Decidueye', 'Litten', 'Torracat',
    'Incineroar', 'Popplio', 'Brionne', 'Primarina', 'Pikipek', 'Trumbeak',
    'Toucannon', 'Yungoos', 'Gumshoos', 'Grubbin', 'Charjabug', 'Vikavolt',
    'Crabrawler', 'Crabominable', 'Oricorio', 'Cutiefly', 'Ribombee', 'Rockruff',
    'Lycanroc', 'Wishiwashi', 'Mareanie', 'Toxapex', 'Mudbray', 'Mudsdale',
    'Dewpider', 'Araquanid', 'Fomantis', 'Lurantis', 'Morelull', 'Shiinotic',
    'Salandit', 'Salazzle', 'Stufful', 'Bewear', 'Bounsweet', 'Steenee',
    'Tsareena', 'Comfey', 'Oranguru', 'Passimian', 'Wimpod', 'Golisopod',
    'Sandygast', 'Palossand', 'Pyukumuku', 'Type: Null', 'Silvally', 'Minior',
    'Komala', 'Turtonator', 'Togedemaru', 'Mimikyu', 'Bruxish', 'Drampa',
    'Dhelmise', 'Jangmo-o', 'Hakamo-o', 'Kommo-o', 'Tapu Koko', 'Tapu Lele',
    'Tapu Bulu', 'Tapu Fini', 'Cosmog', 'Cosmoem', 'Solgaleo', 'Lunala',
    'Nihilego', 'Buzzwole', 'Pheromosa', 'Xurkitree', 'Celesteela', 'Kartana',
    'Guzzlord', 'Necrozma', 'Magearna', 'Marshadow', 'Poipole', 'Naganadel',
    'Stakataka', 'Blacephalon', 'Zeraora', 'Meltan', 'Melmetal', 'Grookey',
    'Thwackey', 'Rillaboom', 'Scorbunny', 'Raboot', 'Cinderace', 'Sobble',
    'Drizzile', 'Inteleon', 'Skwovet', 'Greedent', 'Rookidee', 'Corvisquire',
    'Corviknight', 'Blipbug', 'Dottler', 'Orbeetle', 'Nickit', 'Thievul',
    'Gossifleur', 'Eldegoss', 'Wooloo', 'Dubwool', 'Chewtle', 'Drednaw',
    'Yamper', 'Boltund', 'Rolycoly', 'Carkol', 'Coalossal', 'Applin',
    'Flapple', 'Appletun', 'Silicobra', 'Sandaconda', 'Cramorant', 'Arrokuda',
    'Barraskewda', 'Toxel', 'Toxtricity', 'Sizzlipede', 'Centiskorch', 'Clobbopus',
    'Grapploct', 'Sinistea', 'Polteageist', 'Hatenna', 'Hattrem', 'Hatterene',
    'Impidimp', 'Morgrem', 'Grimmsnarl', 'Obstagoon', 'Perrserker', 'Cursola',
    "Sirfetch'd", 'Mr. Rime', 'Runerigus', 'Milcery', 'Alcremie', 'Falinks',
    'Pincurchin', 'Snom', 'Frosmoth', 'Stonjourner', 'Eiscue', 'Indeedee',
    'Morpeko', 'Cufant', 'Copperajah', 'Dracozolt', 'Arctozolt', 'Dracovish',
    'Arctovish', 'Duraludon', 'Dreepy', 'Drakloak', 'Dragapult', 'Zacian',
    'Zamazenta', 'Eternatus', 'Kubfu', 'Urshifu', 'Zarude', 'Regieleki',
    'Regidrago', 'Glastrier', 'Spectrier', 'Calyrex', 'Wyrdeer', 'Kleavor',
    'Ursaluna', 'Basculegion', 'Sneasler', 'Overqwil', 'Enamorus', 'Sprigatito',
    'Floragato', 'Meowscarada', 'Fuecoco', 'Crocalor', 'Skeledirge', 'Quaxly',
    'Quaxwell', 'Quaquaval', 'Lechonk', 'Oinkologne', 'Tarountula', 'Spidops',
    'Nymble', 'Lokix', 'Pawmi', 'Pawmo', 'Pawmot', 'Tandemaus',
    'Maushold', 'Fidough', 'Dachsbun', 'Smoliv', 'Dolliv', 'Arboliva',
    'Squawkabilly', 'Nacli', 'Naclstack', 'Garganacl', 'Charcadet', 'Armarouge',
    'Ceruledge', 'Tadbulb', 'Bellibolt', 'Wattrel', 'Kilowattrel', 'Maschiff',
    'Mabosstiff', 'Shroodle', 'Grafaiai', 'Bramblin', 'Brambleghast', 'Toedscool',
    'Toedscruel', 'Klawf', 'Capsakid', 'Scovillain', 'Rellor', 'Rabsca',
    'Flittle', 'Espathra', 'Tinkatink', 'Tinkatuff', 'Tinkaton', 'Wiglett',
    'Wugtrio', 'Bombirdier', 'Finizen', 'Palafin', 'Varoom', 'Revavroom',
    'Cyclizar', 'Orthworm', 'Glimmet', 'Glimmora', 'Greavard', 'Houndstone',
    'Flamigo', 'Cetoddle', 'Cetitan', 'Veluza', 'Dondozo', 'Tatsugiri',
    'Annihilape', 'Clodsire', 'Farigiraf', 'Dudunsparce', 'Kingambit', 'Great Tusk',
    'Scream Tail', 'Brute Bonnet', 'Flutter Mane', 'Slither Wing', 'Sandy Shocks', 'Iron Treads',
    'Iron Bundle', 'Iron Hands', 'Iron Jugulis', 'Iron Moth', 'Iron Thorns', 'Frigibax',
    'Arctibax', 'Baxcalibur', 'Gimmighoul', 'Gholdengo', 'Wo-Chien', 'Chien-Pao',
    'Ting-Lu', 'Chi-Yu', 'Roaring Moon', 'Iron Valiant', 'Koraidon', 'Miraidon',
    'Walking Wake', 'Iron Leaves', 'Dipplin', 'Poltchageist', 'Sinistcha', 'Okidogi',
    'Munkidori', 'Fezandipiti', 'Ogerpon', 'Archaludon', 'Hydrapple', 'Gouging Fire',
    'Raging Bolt', 'Iron Boulder', 'Iron Crown', 'Terapagos', 'Pecharunt',
]

assert len(NATIONAL_NAMES) == 1025, f"national roster is 1025 names, got {len(NATIONAL_NAMES)}"

# Per-id bucket index. One digit per id mapping into _BUCKET_LABELS:
#   0 = male / male-majority / 50-50 default, 1 = female-majority / female,
#   2 = genderless. Compact string keeps this file scannable.
_BUCKET_LABELS: tuple[str, ...] = (
    'totalMalePokemonCaptured',
    'totalFemalePokemonCaptured',
    'totalGenderlessPokemonCaptured',
)

_BUCKET_INDEX: str = (
    '00000000000000000000000000001110001111110000000000000000000000000000000000000000'
    '22000000000000000002200000000000101000022001000000020000200000022200022000000000'
    '00000000000011000000000000000000000000002000000011000000000001000000000020000100'
    '11222000222000000000000000000000000000000000000000020000010110000000000001000000'
    '00000000000000002200002200000000000000000000000001000222222102222200000000000000'
    '00000000000010010000000000000011000220010000000000000000000002000000000002000122'
    '22220221222222000000000000000000000000000000000000000000000000000001100000000000'
    '00000000000111110000000000000000000000222000000000000020000002200000110000000222'
    '00220222200000000000000000111110000000000000000000000000000000200000000000022222'
    '20000000000000000000100000000000000001001111000000022200000020002222222222222222'
    '22222222200000000000000000000000000000000000000000000221110000010001120000000002'
    '22200002220022222200000010000000000000000002200000000000000000000000000000001110'
    '00000000000000000000000222222222222000222222222222022000100222202'
)
assert len(_BUCKET_INDEX) == 1025

def _coerce_pid(pid: int | float | str) -> int | None:
    """Some saves emit ``id`` as a float or string; cast defensively."""
    try:
        return int(pid)
    except (TypeError, ValueError):
        return None


def name_for(pid: int | float | str) -> str:
    """Return a friendly name for a national-dex id, or '?' if unknown."""
    idx = _coerce_pid(pid)
    if idx is not None and 1 <= idx <= len(NATIONAL_NAMES):
        return NATIONAL_NAMES[idx - 1]
    return "?"


def region_for(pid: int | float | str) -> str:
    """Return the region label for a national-dex id, or '?' if unknown."""
    idx = _coerce_pid(pid)
    if idx is None:
        return "?"
    for label, lo, hi in REGION_RANGES:
        if lo <= idx <= hi:
            return label
    return "?"


def stat_bucket_for(pid: int | float | str) -> str | None:
    """Return the ``save.statistics`` counter key to bump for this species.

    One of:
      - ``"totalMalePokemonCaptured"`` — male-only or male-majority.
      - ``"totalFemalePokemonCaptured"`` — female-majority or female-only.
      - ``"totalGenderlessPokemonCaptured"`` — no gender (legendaries, fossils,
        Magnemite line, etc.).

    Returns ``None`` when ``pid`` is outside the table; callers should bump
    only the gender-neutral total in that case.
    """
    idx = _coerce_pid(pid)
    if idx is not None and 1 <= idx <= len(_BUCKET_INDEX):
        return _BUCKET_LABELS[int(_BUCKET_INDEX[idx - 1])]
    return None


# Backward-compat alias for callers that still import KANTO_NAMES.
KANTO_NAMES = NATIONAL_NAMES[:151]

